# Generated by Django 3.2.7 on 2021-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.CharField(default='', max_length=500),
        ),
    ]
